Repository eslint/rfcs, pull requests merged in 2020-07, with the labels that each got.

#61 Docs: Update RFC process based on TSC meeting discussion
  README.md
Labels: documentation

#9 Config File Simplification
  designs/2018-processors-improvements/README.md
  designs/2019-config-simplification/README.md
Labels: Final Commenting, feature

#62 Docs: Clarify RFC approval completeness guideline
  README.md
Labels: triage

#57 Accessing `cwd` from formatters
  designs/2020-cwd-in-formatters/README.md
Labels: Final Commenting
